; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[addanother][subdir] = "contrib"
projects[addanother][version] = "2.1"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta3"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Modules
projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[dialog][subdir] = "contrib"
projects[dialog][version] = "1.x-dev"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[media][subdir] = "contrib"
projects[media][version] = "1.2"

projects[filter_tips_dialog][subdir] = "contrib"
projects[filter_tips_dialog][version] = "1.x-dev"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "1.1"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.8"

projects[i18_page_views][subdir] = "contrib"
projects[i18_page_views][version] = "1.1"

projects[i18nviews][subdir] = "contrib"
projects[i18nviews][version] = "3.x-dev"

projects[l10n_client][subdir] = "contrib"
projects[l10n_client][version] = "1.1"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet][download][type] = ""
libraries[leaflet][download][url] = ""
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

; Modules
projects[leaflet_more_maps][subdir] = "contrib"
projects[leaflet_more_maps][version] = "1.2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.0"

projects[media_browser_plus][subdir] = "contrib"
projects[media_browser_plus][version] = "1.0-beta3"

projects[media_colorbox][subdir] = "contrib"
projects[media_colorbox][version] = "1.0-rc3"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "1.0-beta3"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[rotating_banner][subdir] = "contrib"
projects[rotating_banner][version] = "2.x-dev"

projects[taxonomy_manager][subdir] = "contrib"
projects[taxonomy_manager][version] = "1.0-rc1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.1"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.2"

projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[works_and_projects][download][type] = ""
projects[works_and_projects][download][url] = ""
projects[works_and_projects][type] = "module"
projects[works_and_projects][subdir] = "custom/features"
projects[works_and_projects][version] = "1.0"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[blossom-admin][version] = "1.0"

projects[BaseBuildingBlocks][type] = "theme"
projects[BaseBuildingBlocks][download][type] = "git"
projects[BaseBuildingBlocks][download][url] = "https://github.com/patrickocoffeyo/BaseBuildingBlocks.git"
projects[BaseBuildingBlocks][download][revision] = "eec03ad88a47090d03706155f732e3b869abfe83"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet_markercluster][download][type] = ""
libraries[leaflet_markercluster][download][url] = ""
libraries[leaflet_markercluster][directory_name] = "leaflet_markercluster"
libraries[leaflet_markercluster][type] = "library"

